//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bh_GiftCode
    {
        public string bh_masp { get; set; }
        public string bh_giftcode1 { get; set; }
        public Nullable<System.DateTime> bh_datecreate { get; set; }
        public Nullable<System.DateTime> bh_dateend { get; set; }
        public Nullable<int> bh_point { get; set; }
        public Nullable<int> status { get; set; }
    }
}
