//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bh_GiftProduct
    {
        public long id { get; set; }
        public string bh_name { get; set; }
        public string bh_key { get; set; }
        public string bh_des { get; set; }
        public Nullable<int> bh_quantity { get; set; }
        public string bh_unit { get; set; }
        public Nullable<int> bh_price { get; set; }
        public string bh_image_before { get; set; }
        public Nullable<int> bh_status { get; set; }
    }
}
