//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bh_UserProduct
    {
        public long id { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<long> bh_id { get; set; }
        public Nullable<int> bh_type { get; set; }
        public Nullable<int> bh_qt { get; set; }
        public Nullable<int> bh_price { get; set; }
        public string bh_unit { get; set; }
        public Nullable<System.DateTime> bh_date { get; set; }
    }
}
