//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctr_steel
    {
        public string ctr_name { get; set; }
        public string ctr_request_default { get; set; }
        public string ctr_page_name { get; set; }
        public int ctr_type { get; set; }
        public int id_ctr { get; set; }
        public string ctr_client_id { get; set; }
        public Nullable<int> id_project { get; set; }
        public string ctr_des { get; set; }
        public string ctr_store_default { get; set; }
        public string ctr_placeholder { get; set; }
        public string ctr_placeholder_us { get; set; }
        public string ctr_name_us { get; set; }
        public string ctr_code_js { get; set; }
        public string ctr_img { get; set; }
        public Nullable<bool> ctr_require_validate { get; set; }
        public string ctr_require_validate_rex { get; set; }
        public string ctr_require_validate_mess { get; set; }
    }
}
