//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctr_in_form
    {
        public int id_ctr { get; set; }
        public int id_form { get; set; }
        public int order_ctr { get; set; }
        public string ctr_client_id { get; set; }
        public string ctr_store { get; set; }
        public string ctr_name { get; set; }
        public int id_ctr_in_form { get; set; }
        public string ctr_placeholder { get; set; }
        public string ctr_name_us { get; set; }
        public string ctr_placeholder_us { get; set; }
        public string ctr_parent_active { get; set; }
        public string ctr_effect_show { get; set; }
        public string ctr_query_data { get; set; }
        public Nullable<bool> ctr_require_validate { get; set; }
        public string ctr_require_validate_rex { get; set; }
        public string ctr_require_validate_mess { get; set; }
    }
}
