//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhongMachEntities : DbContext
    {
        public PhongMachEntities()
            : base("name=PhongMachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bh_GiftCode> bh_GiftCode { get; set; }
        public virtual DbSet<bh_GiftProduct> bh_GiftProduct { get; set; }
        public virtual DbSet<bh_UserGiftCode> bh_UserGiftCode { get; set; }
        public virtual DbSet<bh_UserProduct> bh_UserProduct { get; set; }
        public virtual DbSet<ctr_in_form> ctr_in_form { get; set; }
        public virtual DbSet<ctr_steel> ctr_steel { get; set; }
        public virtual DbSet<form_steel> form_steel { get; set; }
        public virtual DbSet<form_store> form_store { get; set; }
        public virtual DbSet<form_store_para> form_store_para { get; set; }
        public virtual DbSet<fs_auth> fs_auth { get; set; }
        public virtual DbSet<fs_manga> fs_manga { get; set; }
        public virtual DbSet<fs_manga_chap> fs_manga_chap { get; set; }
        public virtual DbSet<fs_manga_tag> fs_manga_tag { get; set; }
        public virtual DbSet<fs_manga_type> fs_manga_type { get; set; }
        public virtual DbSet<mar_project> mar_project { get; set; }
        public virtual DbSet<other_group> other_group { get; set; }
        public virtual DbSet<other_item> other_item { get; set; }
        public virtual DbSet<other_list> other_list { get; set; }
        public virtual DbSet<pct_department> pct_department { get; set; }
        public virtual DbSet<pct_employee> pct_employee { get; set; }
        public virtual DbSet<pct_ticket> pct_ticket { get; set; }
        public virtual DbSet<pct_title> pct_title { get; set; }
        public virtual DbSet<project_steel> project_steel { get; set; }
        public virtual DbSet<so_orther> so_orther { get; set; }
        public virtual DbSet<so_orther_detail> so_orther_detail { get; set; }
        public virtual DbSet<so_prod_image_detail> so_prod_image_detail { get; set; }
        public virtual DbSet<store_> store_ { get; set; }
        public virtual DbSet<store_cate> store_cate { get; set; }
        public virtual DbSet<store_com_ship> store_com_ship { get; set; }
        public virtual DbSet<store_com_type> store_com_type { get; set; }
        public virtual DbSet<store_company> store_company { get; set; }
        public virtual DbSet<store_contact> store_contact { get; set; }
        public virtual DbSet<store_exp> store_exp { get; set; }
        public virtual DbSet<store_imp> store_imp { get; set; }
        public virtual DbSet<store_prod> store_prod { get; set; }
        public virtual DbSet<store_prod_sku> store_prod_sku { get; set; }
        public virtual DbSet<store_slot> store_slot { get; set; }
        public virtual DbSet<store_stock> store_stock { get; set; }
        public virtual DbSet<store_unit> store_unit { get; set; }
        public virtual DbSet<sys_company> sys_company { get; set; }
        public virtual DbSet<sys_fs_help> sys_fs_help { get; set; }
        public virtual DbSet<sys_gridview_control> sys_gridview_control { get; set; }
        public virtual DbSet<sys_group_page> sys_group_page { get; set; }
        public virtual DbSet<sys_info> sys_info { get; set; }
        public virtual DbSet<sys_mapped_col> sys_mapped_col { get; set; }
        public virtual DbSet<sys_mapped_join> sys_mapped_join { get; set; }
        public virtual DbSet<sys_mapped_operators> sys_mapped_operators { get; set; }
        public virtual DbSet<sys_mapped_table> sys_mapped_table { get; set; }
        public virtual DbSet<sys_mapped_ty_op> sys_mapped_ty_op { get; set; }
        public virtual DbSet<sys_mapped_type> sys_mapped_type { get; set; }
        public virtual DbSet<sys_page> sys_page { get; set; }
        public virtual DbSet<tbl_menu_PM> tbl_menu_PM { get; set; }
        public virtual DbSet<tbl_new_PM> tbl_new_PM { get; set; }
        public virtual DbSet<tbl_silde_PM> tbl_silde_PM { get; set; }
        public virtual DbSet<tbl_type_new_PM> tbl_type_new_PM { get; set; }
        public virtual DbSet<tblSysUserGroupPage> tblSysUserGroupPages { get; set; }
        public virtual DbSet<tblSysUserGroupPageDetail> tblSysUserGroupPageDetails { get; set; }
        public virtual DbSet<tblSysUserGroupPagePage> tblSysUserGroupPagePages { get; set; }
        public virtual DbSet<tblSysUserRolePage> tblSysUserRolePages { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserCloud> tblUserClouds { get; set; }
        public virtual DbSet<tblUserFriend> tblUserFriends { get; set; }
        public virtual DbSet<tblUserImg> tblUserImgs { get; set; }
        public virtual DbSet<user_steel> user_steel { get; set; }
        public virtual DbSet<web_banner> web_banner { get; set; }
        public virtual DbSet<web_chater> web_chater { get; set; }
        public virtual DbSet<web_chater_content> web_chater_content { get; set; }
        public virtual DbSet<web_content> web_content { get; set; }
        public virtual DbSet<web_content_other> web_content_other { get; set; }
        public virtual DbSet<web_customer> web_customer { get; set; }
        public virtual DbSet<web_department> web_department { get; set; }
        public virtual DbSet<web_employer> web_employer { get; set; }
        public virtual DbSet<web_list_product> web_list_product { get; set; }
        public virtual DbSet<web_menu_root> web_menu_root { get; set; }
        public virtual DbSet<web_products> web_products { get; set; }
        public virtual DbSet<web_title> web_title { get; set; }
        public virtual DbSet<fs_manga_img> fs_manga_img { get; set; }
        public virtual DbSet<grid_view_mapping> grid_view_mapping { get; set; }
        public virtual DbSet<log_store_prod> log_store_prod { get; set; }
        public virtual DbSet<sys_data_fixed> sys_data_fixed { get; set; }
        public virtual DbSet<sys_store_prod> sys_store_prod { get; set; }
        public virtual DbSet<wb_advertising> wb_advertising { get; set; }
        public virtual DbSet<wb_banner> wb_banner { get; set; }
        public virtual DbSet<wb_comment> wb_comment { get; set; }
        public virtual DbSet<wb_menu> wb_menu { get; set; }
        public virtual DbSet<wb_menu_products> wb_menu_products { get; set; }
        public virtual DbSet<wb_products> wb_products { get; set; }
        public virtual DbSet<web_tr_menu_product> web_tr_menu_product { get; set; }
        public virtual DbSet<web_tr_menutop> web_tr_menutop { get; set; }
        public virtual DbSet<web_tr_products> web_tr_products { get; set; }
        public virtual DbSet<web_tr_quangcao> web_tr_quangcao { get; set; }
        public virtual DbSet<tbl_Email> tbl_Email { get; set; }
    }
}
