//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_steel
    {
        public int id_form { get; set; }
        public string form_name { get; set; }
        public Nullable<int> id_project { get; set; }
        public string form_grid_view { get; set; }
        public string form_name_us { get; set; }
        public Nullable<int> form_view_store { get; set; }
        public string form_grid_chart { get; set; }
        public string form_grid_form { get; set; }
        public Nullable<int> form_db { get; set; }
        public string fs_table_name { get; set; }
        public string fs_store_c_u_d_s { get; set; }
        public string fs_script_page_load { get; set; }
    }
}
