//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_store
    {
        public int id_form_store { get; set; }
        public string form_store_code { get; set; }
        public Nullable<int> form_store_type { get; set; }
        public Nullable<int> form_store_admin { get; set; }
    }
}
