//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fs_manga
    {
        public long manga_id { get; set; }
        public string manga_name { get; set; }
        public string manga_key { get; set; }
        public Nullable<long> type_id { get; set; }
        public string manga_des { get; set; }
        public string manga_img { get; set; }
        public Nullable<int> manga_view { get; set; }
        public Nullable<int> manga_status { get; set; }
        public Nullable<System.DateTime> manga_create { get; set; }
        public Nullable<long> auth_id { get; set; }
    }
}
