//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_store_prod
    {
        public int id_store_prod { get; set; }
        public string store_prod_name { get; set; }
        public string store_prod_code { get; set; }
        public string store_prod_img { get; set; }
        public int store_prod_count { get; set; }
        public int store_prod_cost { get; set; }
        public int store_prod_cost_sell { get; set; }
        public int store_prod_shelf { get; set; }
        public System.DateTime log_sell { get; set; }
        public int id_store_cate { get; set; }
        public string store_cate_name { get; set; }
        public int id_store_unit { get; set; }
        public string store_unit_name { get; set; }
        public int id_store { get; set; }
        public string store_name { get; set; }
        public int id_store_stock { get; set; }
        public string store_stock_code { get; set; }
        public int id_store_slot { get; set; }
        public string store_slot_code { get; set; }
    }
}
