//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mar_project
    {
        public int id_mar_project { get; set; }
        public string mar_project_name { get; set; }
        public Nullable<int> mar_project_status { get; set; }
        public System.DateTime mar_project_begin { get; set; }
        public System.DateTime mar_project_end { get; set; }
        public Nullable<int> mar_project_sell_off { get; set; }
        public Nullable<int> mar_project_sell_type { get; set; }
    }
}
