//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class other_item
    {
        public int id_other { get; set; }
        public string other_name { get; set; }
        public Nullable<int> other_status { get; set; }
        public int id_list_other { get; set; }
        public Nullable<int> other_order { get; set; }
    }
}
