//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class other_group
    {
        public int id_group_other { get; set; }
        public string group_other_name { get; set; }
        public Nullable<int> group_other_status { get; set; }
        public Nullable<int> group_other_admin { get; set; }
    }
}
