//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pct_employee
    {
        public int id_employee { get; set; }
        public int id_title { get; set; }
        public string employee_name { get; set; }
        public string employee_address { get; set; }
        public string employee_mobile { get; set; }
    }
}
