//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pct_ticket
    {
        public int id_ticket { get; set; }
        public int id_employee { get; set; }
        public string ticket_fromdate { get; set; }
        public string ticket_todate { get; set; }
        public int ticket_money { get; set; }
        public string ticket_add { get; set; }
        public string ticket_note { get; set; }
    }
}
