//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class so_orther_detail
    {
        public int so_orther_id { get; set; }
        public int so_prod_id { get; set; }
        public int so_prod_count_id { get; set; }
        public int so_prod_price { get; set; }
    }
}
