//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class so_orther
    {
        public int so_id { get; set; }
        public string so_code { get; set; }
        public Nullable<System.DateTime> so_date { get; set; }
        public int so_user_id { get; set; }
        public Nullable<int> so_sms_status { get; set; }
        public string so_fullname { get; set; }
        public string so_email { get; set; }
        public string so_phone_number { get; set; }
        public string so_address { get; set; }
    }
}
