//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class so_prod_image_detail
    {
        public int id { get; set; }
        public string so_image { get; set; }
        public Nullable<int> so_orther { get; set; }
        public Nullable<int> so_id_prod { get; set; }
    }
}
