//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_imp
    {
        public int id_store_imp { get; set; }
        public string store_imp_name { get; set; }
        public Nullable<int> store_imp_checker { get; set; }
        public Nullable<int> store_imp_creater { get; set; }
        public string store_imp_list_data { get; set; }
        public Nullable<int> store_imp_store { get; set; }
    }
}
