//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_com_type
    {
        public int id_store_com_type { get; set; }
        public string type_name { get; set; }
    }
}
