//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_cate
    {
        public int id_store_cate { get; set; }
        public string store_cate_name { get; set; }
        public Nullable<int> store_cate_order { get; set; }
        public Nullable<int> store_cate_status { get; set; }
        public string store_cate_key { get; set; }
        public string store_cate_img { get; set; }
    }
}
