//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_prod_sku
    {
        public int id_store_prod_sku { get; set; }
        public int id_store_prod { get; set; }
        public int sku_count { get; set; }
        public int id_prod_sku { get; set; }
    }
}
