//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_
    {
        public int id_store { get; set; }
        public string store_name { get; set; }
        public string store_ads { get; set; }
        public string store_phone { get; set; }
        public string store_des { get; set; }
    }
}
