//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_company
    {
        public int id_store_company { get; set; }
        public string company_name { get; set; }
        public string company_code { get; set; }
        public string company_address { get; set; }
        public string company_phone { get; set; }
        public string company_email { get; set; }
        public string company_website { get; set; }
        public string company_logo { get; set; }
        public string company_des { get; set; }
        public Nullable<int> id_store_com_type { get; set; }
        public string company_fax { get; set; }
        public string company_bank { get; set; }
        public string company_bank_ads { get; set; }
    }
}
