//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_exp
    {
        public int id_store_exp { get; set; }
        public string store_exp_name { get; set; }
        public string store_exp_list_data { get; set; }
        public Nullable<int> store_exp_creater { get; set; }
        public Nullable<int> store_exp_checker { get; set; }
        public Nullable<int> store_exp_cost { get; set; }
    }
}
