//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_stock
    {
        public int id_store_stock { get; set; }
        public string store_stock_code { get; set; }
        public Nullable<int> store_stock_status { get; set; }
        public Nullable<int> store_stock_store { get; set; }
    }
}
