//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_contact
    {
        public int id_store_contact { get; set; }
        public Nullable<int> id_store_company { get; set; }
        public string contact_full_name { get; set; }
        public string contact_chat { get; set; }
        public string contact_mobile { get; set; }
        public string contact_title { get; set; }
        public string contact_ext { get; set; }
        public string contact_email { get; set; }
    }
}
