//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_slot
    {
        public int id_store_slot { get; set; }
        public Nullable<int> id_store { get; set; }
        public string store_slot_code { get; set; }
        public Nullable<int> id_store_stock { get; set; }
        public Nullable<int> store_slot_contain { get; set; }
    }
}
