//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_prod
    {
        public int id_store_prod { get; set; }
        public string store_prod_name { get; set; }
        public int id_store_unit { get; set; }
        public string store_prod_img { get; set; }
        public string store_prod_code { get; set; }
        public Nullable<int> id_store_cate { get; set; }
        public int store_prod_cost { get; set; }
    }
}
