//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_store_prod
    {
        public int id_store_prod { get; set; }
        public int store_prod_count { get; set; }
        public int id_store_slot { get; set; }
        public int store_prod_cost { get; set; }
        public System.DateTime store_prod_shelf { get; set; }
    }
}
