//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_mapped_col
    {
        public int id_mapped_col { get; set; }
        public Nullable<int> id_mapped { get; set; }
        public string mapped_col_name { get; set; }
        public string mapped_col_type { get; set; }
        public Nullable<int> mapped_col_key { get; set; }
        public string mapped_col_code { get; set; }
        public Nullable<int> mapped_col_order { get; set; }
    }
}
