//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_data_fixed
    {
        public string ctr_client_id { get; set; }
        public Nullable<int> record_order { get; set; }
        public string st_value { get; set; }
        public string st_name { get; set; }
        public string st_parent { get; set; }
        public string ctr_key_query { get; set; }
        public Nullable<int> id_form { get; set; }
    }
}
