//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_mapped_operators
    {
        public int id_operators { get; set; }
        public string operators_name { get; set; }
        public string operators_label { get; set; }
        public string operators_cardinality { get; set; }
    }
}
