//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_gridview_control
    {
        public string table_name { get; set; }
        public string column_name { get; set; }
        public string column_caption { get; set; }
        public Nullable<bool> column_key { get; set; }
        public Nullable<bool> column_edit { get; set; }
    }
}
