//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_info
    {
        public int id_sys_info { get; set; }
        public string sys_info_name { get; set; }
        public string sys_info_des { get; set; }
        public Nullable<int> sys_info_key { get; set; }
    }
}
