//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_group_page
    {
        public int id_group_page { get; set; }
        public string group_page_name { get; set; }
        public Nullable<int> group_page_status { get; set; }
        public Nullable<int> group_page_order { get; set; }
        public string group_page_icon { get; set; }
    }
}
