//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_page
    {
        public int id_page { get; set; }
        public string page_name { get; set; }
        public Nullable<int> id_form { get; set; }
        public Nullable<int> page_order { get; set; }
        public Nullable<int> id_group_page { get; set; }
    }
}
