//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_menu_PM
    {
        public int ID_menu_PM { get; set; }
        public string Name_menu_PM { get; set; }
        public string Link_menu_PM { get; set; }
        public Nullable<int> Type_menu_PM { get; set; }
        public Nullable<int> Status_menu_PM { get; set; }
        public Nullable<int> Order_menu_PM { get; set; }
    }
}
