//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_new_PM
    {
        public int ID_new_PM { get; set; }
        public string Title_new_PM { get; set; }
        public Nullable<int> Status_new_PM { get; set; }
        public string Shortdescription_new_PM { get; set; }
        public string Description { get; set; }
        public string Img_new_PM { get; set; }
        public Nullable<int> Order_new_PM { get; set; }
        public Nullable<int> Img1_new_PM { get; set; }
        public string Img1_new_PM_ { get; set; }
        public Nullable<System.DateTime> Ceatedtime_new_PM { get; set; }
        public Nullable<int> Type_new_PM { get; set; }
    }
}
