//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_silde_PM
    {
        public int ID_silde_PM { get; set; }
        public string Name_silde_PM { get; set; }
        public string Img_silde_PM { get; set; }
        public Nullable<int> Status_silde_PM { get; set; }
        public Nullable<int> Order_silde_PM { get; set; }
    }
}
