//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysUserGroupPageDetail
    {
        public int role_group_page_id { get; set; }
        public int user_id { get; set; }
        public int id_company { get; set; }
        public int id_group_user_detail { get; set; }
    }
}
