//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysUserRolePage
    {
        public int id_page { get; set; }
        public int user_id { get; set; }
        public int role_page_view { get; set; }
        public int role_page_create { get; set; }
        public int role_page_del { get; set; }
        public int role_page_config { get; set; }
        public int role_page_role { get; set; }
        public int id_company { get; set; }
        public int id_user_role_page { get; set; }
    }
}
