//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserCloud
    {
        public long user_cloud_id { get; set; }
        public string user_code { get; set; }
        public string user_birthday { get; set; }
        public string user_code_country { get; set; }
        public string user_gender { get; set; }
        public string user_id_facebook { get; set; }
        public string user_email { get; set; }
        public string user_fullname { get; set; }
        public string user_fname { get; set; }
        public string user_lname { get; set; }
        public string user_avatar { get; set; }
        public string user_type { get; set; }
        public Nullable<long> user_id { get; set; }
    }
}
