//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserFriend
    {
        public long user_id { get; set; }
        public string social_id { get; set; }
        public string social_user { get; set; }
        public string social_type { get; set; }
        public string social_name { get; set; }
        public string social_picture { get; set; }
    }
}
