//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public long user_id { get; set; }
        public string user_email { get; set; }
        public string user_pass { get; set; }
        public string user_fullname { get; set; }
        public Nullable<int> user_status { get; set; }
        public Nullable<System.DateTime> user_create { get; set; }
        public Nullable<System.DateTime> user_update { get; set; }
        public Nullable<int> id_group_user { get; set; }
        public string user_img { get; set; }
        public Nullable<int> user_vip { get; set; }
        public Nullable<System.DateTime> user_vip_end { get; set; }
        public Nullable<int> user_role { get; set; }
        public string forget_pass { get; set; }
        public Nullable<int> user_money { get; set; }
        public string user_avatar { get; set; }
        public Nullable<int> user_online { get; set; }
        public Nullable<int> id_company { get; set; }
        public Nullable<int> user_disk { get; set; }
        public string user_code { get; set; }
        public string seri_number { get; set; }
        public string user_birthday { get; set; }
        public string user_code_country { get; set; }
        public string user_gender { get; set; }
        public string user_id_facebook { get; set; }
        public Nullable<int> user_point { get; set; }
    }
}
