//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserImg
    {
        public long id_user_img { get; set; }
        public string user_img_name { get; set; }
        public string user_img_sexy_key { get; set; }
        public Nullable<double> user_img_size { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<System.DateTime> user_img_create { get; set; }
        public Nullable<double> user_img_w { get; set; }
        public Nullable<double> user_img_h { get; set; }
        public Nullable<int> user_img_type { get; set; }
        public Nullable<int> admin_view { get; set; }
    }
}
