//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_steel
    {
        public int id_user { get; set; }
        public string user_first_name { get; set; }
        public string user_last_name { get; set; }
        public string user_full_name { get; set; }
        public string user_email { get; set; }
        public int user_status { get; set; }
        public string user_pass { get; set; }
    }
}
