//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wb_banner
    {
        public int id_banner { get; set; }
        public string name_banner { get; set; }
        public string links_banner { get; set; }
        public Nullable<int> order_banner { get; set; }
        public string image_banner { get; set; }
        public Nullable<int> status_banner { get; set; }
    }
}
