//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wb_comment
    {
        public int id_comment { get; set; }
        public string noidung_comment { get; set; }
        public Nullable<int> id_products { get; set; }
        public string phone { get; set; }
        public string name_full { get; set; }
        public string email { get; set; }
    }
}
