//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wb_menu_products
    {
        public int id_menu_products { get; set; }
        public string menu_products_name { get; set; }
        public string menu_products_key { get; set; }
        public Nullable<int> menu_products_order { get; set; }
        public string img_products { get; set; }
        public string menu_status { get; set; }
        public string menu_tomtat { get; set; }
        public string menu_noidung { get; set; }
    }
}
