//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wb_products
    {
        public int id_products { get; set; }
        public string name_products { get; set; }
        public string type_products { get; set; }
        public string tomtat_products { get; set; }
        public string noidung_products { get; set; }
        public string price_products { get; set; }
        public string giamgia_products { get; set; }
        public string giasaugiam_products { get; set; }
        public string status_products { get; set; }
        public string img_main_products { get; set; }
        public string order_products { get; set; }
        public string img1_products { get; set; }
        public string img2_products { get; set; }
        public string img3_products { get; set; }
        public string img4_products { get; set; }
        public string tieubieu_products { get; set; }
    }
}
