//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_chater_content
    {
        public long id_chater { get; set; }
        public int id_employer { get; set; }
        public string chater_content { get; set; }
        public System.DateTime chater_content_create { get; set; }
        public long id_up { get; set; }
    }
}
