//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_menu_root
    {
        public int id_menu { get; set; }
        public string menu_name { get; set; }
        public int menu_order { get; set; }
        public string menu_code { get; set; }
        public string banner_tiny { get; set; }
        public int menu_status { get; set; }
    }
}
