//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_tr_quangcao
    {
        public int id_quangcao { get; set; }
        public string name_quangcao { get; set; }
        public string links_quangcao { get; set; }
        public string status_quangcao { get; set; }
        public Nullable<int> order_quangcao { get; set; }
        public string img_quangcao { get; set; }
        public Nullable<int> type_quangcao { get; set; }
    }
}
