//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_tr_products
    {
        public int id_products_tr { get; set; }
        public string name_product_tr { get; set; }
        public Nullable<int> type_products_tr { get; set; }
        public Nullable<int> status_products_tr { get; set; }
        public Nullable<int> order_products_tr { get; set; }
        public string img_main_products_tr { get; set; }
        public string img1_main_products_tr { get; set; }
        public Nullable<int> Specials { get; set; }
        public string price_products { get; set; }
        public string tomtat_products { get; set; }
        public string noidung_products { get; set; }
        public string img_small_products { get; set; }
        public string img2_main_products_tr { get; set; }
        public string img3_main_products_tr { get; set; }
        public string price_products1 { get; set; }
        public string phantram_products { get; set; }
    }
}
