//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_tr_menutop
    {
        public int id_menu_top { get; set; }
        public string name_menu_top { get; set; }
        public string links_menu_top { get; set; }
        public string key_links_menu_top { get; set; }
        public Nullable<int> status_menu_top { get; set; }
        public Nullable<int> order_menu_top { get; set; }
    }
}
