//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_list_product
    {
        public int id_list_prod { get; set; }
        public string list_prod_name { get; set; }
        public int list_prod_order { get; set; }
        public int list_prod_link { get; set; }
        public int list_prod_status { get; set; }
    }
}
