//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_products
    {
        public int id_prod { get; set; }
        public string prod_name { get; set; }
        public int prod_order { get; set; }
        public int prod_status { get; set; }
        public string prod_content { get; set; }
    }
}
