//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_customer
    {
        public int id_customer { get; set; }
        public string customer_name { get; set; }
        public string customer_logo { get; set; }
        public string customer_prod { get; set; }
        public string customer_idea { get; set; }
        public int customer_order { get; set; }
        public int customer_status { get; set; }
    }
}
