//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_employer
    {
        public int id_employer { get; set; }
        public string employer_name { get; set; }
        public int id_title { get; set; }
        public string employer_code { get; set; }
        public string employer_ext { get; set; }
        public string employer_mobile { get; set; }
        public int employer_status { get; set; }
    }
}
